name: Myapp
on: push
jobs:
    firstjob:
        runs-on: ubuntu-latest
        steps:
          - name: First deploy
            run: echo "Hello Mac kingsley"
          - name: Artifact
            run: mkdir -p path/to/artifact
          - name: file save
            run: echo hello > path/to/artifact/world.txt

          - name: Artifact upload
            uses: actions/upload-artifact@v4
            with:
               name: my-artifact
               path: path/to/artifact/world.txt
              
          - name: Checkout
            uses: actions/checkout@v4

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3



          - name: Docker meta
            id: meta
            uses: docker/metadata-action@v4
            with:
              images: |
                   mackingsley/spaceapp
              tags: |
                type=ref,event=branch
                type=ref,event=pr
                type=semver,pattern={{version}}
                type=semver,pattern={{major}}.{{minor}}
                type=sha




          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
                 username: ${{ secrets.DOCKERHUB_USERNAME }}
                 password: ${{ secrets.DOCKERHUB_PASSWORD }}

           
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
      
          - name: Build and push
            uses: docker/build-push-action@v6
            with:
              push: true
              tags: mackingsley/spaceapp:latest
            
  
