name: Myapp
on: push
jobs:
    firstjob:
        runs-on: [ubuntu-latest,macos,windows]
        steps:
          - name: First deploy
            run: echo "Hello Mac kingsley"
          - name: Artifact
            run: mkdir -p path/to/artifact
          - name: file save
            run: echo hello > path/to/artifact/world.txt

          - name: Artifact uploaf
            uses: actions/upload-artifact@v4
            with:
               name: my-artifact
               path: path/to/artifact/world.txt
            
  
